/**
 * Webhook secret lookup and verification.
 *
 * UptimeRobot webhook secrets are stored in Firestore secretRefs collection as
 * { kind: 'api-key', name: 'uptimerobot-webhook-{monitorId}', secretManagerRef: ... }
 * with a custom field `webhookSecret` (the raw URL token).
 *
 * We store the SHA-256 hash of the token in a dedicated webhookSecrets collection:
 *   webhookSecrets/{hash} → { monitorId, revokedAt? }
 *
 * This avoids scanning the entire secretRefs collection on every webhook hit.
 *
 * The webhook URL is: /api/webhooks/uptimerobot/{rawSecret}
 * On receive: hash rawSecret → lookup webhookSecrets/{hash} → get monitorId.
 */

import 'server-only'
import { createHash } from 'crypto'
import { getAdminDb } from '@/lib/firebase/admin'

export type WebhookSecretDoc = {
  monitorId: string
  revokedAt?: FirebaseFirestore.Timestamp
}

/** SHA-256 hex of the raw secret token */
export function hashWebhookSecret(rawSecret: string): string {
  return createHash('sha256').update(rawSecret).digest('hex')
}

/**
 * Looks up a raw webhook secret and returns the bound monitorId.
 * Returns null if not found or revoked.
 */
export async function lookupWebhookSecret(rawSecret: string): Promise<string | null> {
  const hash = hashWebhookSecret(rawSecret)
  const snap = await getAdminDb().collection('webhookSecrets').doc(hash).get()

  if (!snap.exists) return null

  const data = snap.data() as WebhookSecretDoc
  if (data.revokedAt) return null

  return data.monitorId
}

/**
 * Register a new webhook secret for a monitor.
 * rawSecret is generated by the caller (e.g. crypto.randomBytes(32).toString('hex')).
 * Only the hash is stored.
 */
export async function registerWebhookSecret(
  rawSecret: string,
  monitorId: string,
): Promise<void> {
  const hash = hashWebhookSecret(rawSecret)
  await getAdminDb().collection('webhookSecrets').doc(hash).set({ monitorId })
}

/**
 * Revoke a webhook secret by its hash.
 */
export async function revokeWebhookSecret(rawSecret: string): Promise<void> {
  const hash = hashWebhookSecret(rawSecret)
  const { FieldValue } = await import('firebase-admin/firestore')
  await getAdminDb()
    .collection('webhookSecrets')
    .doc(hash)
    .update({ revokedAt: FieldValue.serverTimestamp() })
}
